// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/changzhijay2/geekbang_go/week04/internal/biz"
	"github.com/changzhijay2/geekbang_go/week04/internal/dao"
	"github.com/changzhijay2/geekbang_go/week04/internal/server"
	"github.com/changzhijay2/geekbang_go/week04/pkg/mysql"
)

// Injectors from wire.go:

func InitServer() (*server.Server, error) {
	db := mysql.NewDB()
	daoDao := dao.NewDao(db)
	bizBiz := biz.NewBiz(daoDao)
	serverServer := server.NewServer(bizBiz)
	return serverServer, nil
}
